"""add deleted_at to sessions

Revision ID: 4d0898ab4756
Revises: 672dcf26c84b
Create Date: 2025-09-24 20:47:51.373500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d0898ab4756'
down_revision: Union[str, Sequence[str], None] = '672dcf26c84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_sessions_deleted_at'), 'sessions', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_deleted_at'), table_name='sessions')
    op.drop_column('sessions', 'deleted_at')
    # ### end Alembic commands ###
